spring:
  #  datasource:
  #    username: S09P12D208
  #    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S09P12D208?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
  #    driverClassName: org.mariadb.jdbc.Driver
  #    password: Pmgwb2y284
  #    hikari:
  #      maximum-pool-size: 3
  datasource:
    url: jdbc:mariadb://localhost:3306/prac_security?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: Hc-5514
    password: 5514
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: mongodb+srv://S09P12D208:xACDfpmiw5@ssafy.ngivl.mongodb.net/S09P12D208?authSource=admin
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
server:
  port: 9091
  servlet:
    jsp:
      init-parameters:
        development: true