#spring:
#  profiles:
#    active: production-set1
#
#---
#
#spring:
#  profiles:
#    group:
#      production-set1:
#        - common
#        - port_9091
#      production-set2:
#        - common
#        - port_9092
#      production-set3:
#        - common
#        - port_9093
#
#---
#
#spring:
#  datasource:
#    username: S09P12D208
#    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S09P12D208?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
#    driverClassName: org.mariadb.jdbc.Driver
#    password: Pmgwb2y284
#    hikari:
#      maximum-pool-size: 3
#  jpa:
#    hibernate:
#      ddl-auto: update
#  data:
#    mongodb:
#      uri: mongodb+srv://S09P12D208:xACDfpmiw5@ssafy.ngivl.mongodb.net/S09P12D208?authSource=admin
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
#  config:
#    activate:
#      on-profile: common
#server:
#  servlet:
#    jsp:
#      init-parameters:
#        development : true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health
#
#---
#
#spring:
#  config:
#    activate:
#      on-profile: port_9091
#
#server:
#  port: 9091
#
#---
#
#spring:
#  config:
#    activate:
#      on-profile: port_9092
#
#server:
#  port: 9092
#
#---
#
#spring:
#  config:
#    activate:
#      on-profile: port_9093
#
#server:
#  port: 9093
#
#---