spring:
  datasource:
    username: S09P12D208
    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S09P12D208?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    driverClassName: org.mariadb.jdbc.Driver
    password: Pmgwb2y284
    hikari:
      maximum-pool-size: 3
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: mongodb+srv://S09P12D208:xACDfpmiw5@ssafy.ngivl.mongodb.net/S09P12D208?authSource=admin
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  redis:
    host: i9d208.p.ssafy.io
    port: 6379
server:
  port: 9091
  servlet:
    jsp:
      init-parameters:
        development: true
springdoc:
  swagger-ui:
    path: /api/api.html

management:
  endpoints:
    web:
      exposure:
        include: health
cloud:
  aws:
    s3:
      bucket: with-view-bucket
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIAQZFCIQLESJZHO4EF
      secretKey: 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
    ses:
      access-key: AKIASOYPQPSFBDSTFBV4
      secret-key: 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

OPENVIDU_URL: https://i9d208.p.ssafy.io:8443/
OPENVIDU_SECRET: ssafy
CLOUD_FRONT_URL: https://dm51j1y1p1ekp.cloudfront.net/
AWS_ACCESS_KEY: AKIAQZFCIQLESJZHO4EF
AWS_SECRET_KEY: fe3XBmE8Vq3s4YYVS
DEFAULT_IMG: logo.png